name: Deploy website to Heroku
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Init projet (git clone)
      - uses: actions/checkout@v2
      # PHP linter
      - uses: michaelw90/PHP-Lint@master
      # Security check
      - uses: symfonycorp/security-checker-action@v2
      # PHP Stan
      - uses: docker://oskarstark/phpstan-ga
        with:
          args: analyse src/ --level=5